### ISSUE TITLE
Can't get data from /pets and position is null in /households/{household_id}/pets/{pet_id}

### ISSUE THREAD

**Issue by rleeden** [fabieu/sureflap-api#77] opened 2024-12-05 12:54 UTC
I'm not sure what changed, but sometime overnight my monitoring of the cat flap stopped working. I'm not sure what changed - whether it's something my hardware, with the api? I'm running the latest version of the docker installation.

It had been working for quite some time, and to get the location of my cat, I was relying on calling: 

`/households/{household_id}/pets/location`

Noticing that things had stopped working this morning, I read in the documentation that use of 'location' had been deprecated, and sotried calling: 

`/pets/{pet_id}/position`

This results in error: 

`{
    "detail": "Not Found"
}
`

As does just calling:

` /pets`

But calling:

`/households/{household_id}/pets/{pet_id}`

works, and does give details of my cat, but unfortunately the position field always seems to remain set to 'null'. Redacted output is as follows:

```
{
    "comments": null,
    "created_at": "2024-05-17T09:04:30Z",
    "gender": 0.0,
    "household_id": XXXXXX.0,
    "id": XXXXXX.0,
    "name": "XXXXXXXX",
    "photo": {
        "created_at": "2024-05-17T09:04:54Z",
        "id": XXXXXXX.0,
        "location": "https://userimages.production.surehub.io/thm/XXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.jpg",
        "updated_at": null,
        "uploading_user_id": XXXXXXXXXX.0,
        "version": 0.0
    },
    "photo_id": XXXXXX.0,
    "position": null,
    "species_id": 1.0,
    "tag_id": XXXXXXX.0,
    "updated_at": "2024-12-04T09:38:03Z",
    "version": 2.0
}
```
Anybody have any idea what's going on? What's changed?

**Comment by ShogunPanda** [comment] 2024-12-05 16:06
Hi!
I'm also experiencing this. I guess they deployed something.

Worst part is that the application still works so they're probably using a different API.
I hope they're not discontinuing this API. Sob.

**Comment by fabieu** [comment] 2024-12-05 16:09
I will have a look at this tomorrow.

**Comment by fabieu** [comment] 2024-12-06 15:51
After further investigation I suspect that Sure PetCare made a mistake on their end. I have two pets in my household. For one of them i get the correct position payload from their API, while for the other one the position payload is missing entirely. Take a look at the following payload from `/households/{household_id}/pets`:

```json
[
  {
    "id": "XXXXXX",
    "name": "Leo",
    "gender": 1,
    "date_of_birth": "1970-01-01T00:00:00Z",
    "weight": "4800",
    "comments": "",
    "breed_id": 382,
    "food_type_id": 3,
    "household_id": "XXXXX",
    "photo_id": "XXXXXX",
    "species_id": 1,
    "spayed": 1,
    "tag_id": "XXXXXX",
    "version": 11,
    "created_at": "2020-11-24T10:44:35Z",
    "updated_at": "2024-11-17T19:31:43Z",,
    "conditions": [],
    "tag": {
      "id": "XXXXXX",
      "tag": "XXX.XXXXXXX",
      "supported_product_ids": [
        3,
        4,
        6,
        8,
        32
      ],
      "version": 310,
      "created_at": "2020-11-24T10:44:35Z",
      "updated_at": "2022-11-09T01:57:20Z"
    },
    "status": {
      "activity": {
        "id": "XXXXXXXXX",
        "pet_id": "XXXXXX",
        "tag_id": "XXXXXX",
        "device_id": "XXXXXX",
        "where": 2,
        "since": "2024-12-04T16:39:47Z"
      }
    },
    "position": {
      "id": "XXXXXXXX",
      "pet_id": "XXXXXX",
      "tag_id": "XXXXXX",
      "device_id": "XXXXXX",
      "where": 2,
      "since": "2024-12-04T16:39:47Z"
    }
  },
  {
    "id": "XXXXXX",
    "name": "Sammy",
    "gender": 1,
    "date_of_birth": "1970-01-01T00:00:00Z",
    "weight": "4800",
    "comments": "",
    "breed_id": 382,
    "food_type_id": 3,
    "household_id": "XXXXX",
    "photo_id": "XXXXXX",
    "species_id": 1,
    "spayed": 1,
    "tag_id": "XXXXXX",
    "version": 11,
    "created_at": "2020-11-24T10:48:44Z",
    "updated_at": "2024-11-17T19:30:17Z",
    "conditions": [],
    "tag": {
      "id": "XXXXXX",
      "tag": "XXX.XXXXXXXXX",
      "supported_product_ids": [
        3,
        4,
        6,
        8,
        32
      ],
      "version": 218,
      "created_at": "2020-11-24T10:48:44Z",
      "updated_at": "2022-11-09T06:03:06Z"
    },
    "status": {}
  }
]
```
> Note: IDs where obfuscated for privacy reasons

Notice that "Leo" has a `status` and `position` attribute, while "Sammy" has an empty `status` and no `position` attribute. Since I am querying the SureHub API directly, there is not additional manipulation involved.

The only thing you can do is to wait until this issue gets fixed by the Sure Petcare developers.

Kind regards
Fabian

**Comment by rleeden** [comment] 2024-12-06 16:10
Thanks for investigating. How odd and slightly frustrating! I wonder if deleting and re-adding a pet is worthwhile? I might give it a try, if things don't start working in a few days time.

Thanks,
Richard

**Comment by alphatrianguli** [comment] 2024-12-06 23:06
Same or similiar problem here - getting a "Internal Server Error" on calling requesting a get from "http://x.x.x.x:8080/pets/position"

**Comment by fabieu** [comment] 2024-12-06 23:08
> Same or similiar problem here - getting a "Internal Server Error" on calling requesting a get from "http://x.x.x.x:8080/pets/position"

Thats due to the missing `position` attribute. I could improve the error handling here, that at least the valid pets are getting returned.

**Comment by alphatrianguli** [comment] 2024-12-07 07:04
> 
> Thats due to the missing `position` attribute. I could improve the error handling here, that at least the valid pets are getting returned.

Thanks for your answer. Was "position" removed or is it also just a current bug/error by SurePet?

**Comment by fabieu** [comment] 2024-12-08 19:05
Since the official Sure Petcare App (https://surepetcare.io) also has problems displaying the position (see the screenshot below) I believe it is a temporary problem. 
![image](https://github.com/user-attachments/assets/772c4142-3547-46ee-98df-98b349966e74)

I also improved the error handling for missing pet positions. From now on the API will throw a HTTP 500 status code with a detailed error message, when no pet position is found.

**Closed** 2024-12-09 22:54 UTC
Labels: bug

**Comment by rleeden** [comment] 2024-12-11 09:29
Just to let you know, things have started working for me sometime over the last 24 hours.

Not sure if it's related to me contacting Sure Petcare regarding the issue you mentioned on the https://surepetcare.io/ dashboard, which has also now started working for me.

Anyway, thanks for looking into this.

**Comment by fabieu** [comment] 2024-12-11 09:43
> I can confirm, that for me the API is now behaving as expected again. Maybe they did not realize their API was broken until you messaged them :D

**Comment by alphatrianguli** [comment] 2024-12-11 09:48
I can confirm that the problem is also solved on my side - my "MagicMirror" display / dashboard is correctly returning my pets location as well as the time, since when they went out or in the house.

Many thanks again for your efforts on this.
